default:
	g++ -O2 -o quicksort_leftmost_longer_first quicksort_leftmost_longer_first.cpp
	g++ -O2 -o quicksort_leftmost_shorter_first quicksort_leftmost_shorter_first.cpp
	g++ -O2 -o quicksort_leftmost_original quicksort_leftmost_original.cpp
	g++ -O2 -o quicksort_median_of_three_longer_first quicksort_median_of_three_longer_first.cpp
	g++ -O2 -o quicksort_median_of_three_shorter_first quicksort_median_of_three_shorter_first.cpp
	g++ -O2 -o quicksort_median_of_three_original quicksort_median_of_three_original.cpp

clean:
	rm quicksort_leftmost_longer_first
	rm quicksort_leftmost_shorter_first
	rm quicksort_leftmost_original
	rm quicksort_median_of_three_longer_first
	rm quicksort_median_of_three_shorter_first
	rm quicksort_median_of_three_original

run:
	./quicksort_leftmost_longer_first
	./quicksort_leftmost_shorter_first
	./quicksort_leftmost_original
	./quicksort_median_of_three_longer_first
	./quicksort_median_of_three_shorter_first
	./quicksort_median_of_three_original